plugins { id 'com.android.application' }

android {
    namespace 'com.dennis.aimusic'
    compileSdk 35
    defaultConfig {
        applicationId 'com.dennis.aimusic.experimental'
        minSdk 29
        targetSdk 34
        versionCode 3
        versionName '0.2.1-experimental'
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies { testImplementation 'junit:junit:4.13.2' }
